### ISSUE TITLE
cy_dag.pyx is missing

### ISSUE THREAD

**Issue by danielhers** [ninjin/nerv#1]
[`setup.py` is trying to use `cy_dag.pyx`](https://github.com/ninjin/nerv/blob/f7646667fbe4e8ff77387406d97dc68a630c13e3/src/nerv/setup.py#L22), but [no such file exists in `cy/`](https://github.com/ninjin/nerv/tree/master/src/nerv/cy/cy_dag.pyx).

**Comment by ninjin** [comment]
Nice catch, removed in 9f55a78.
